### ISSUE TITLE
网页中gif图片不能循环播放的解决方法 | 艾新可思

### ISSUE THREAD

**Issue by iseex** [iseex/iseex.github.io#27]
https://iseex.github.io/2018-08/gif-play/# 

 最近在写博客中发现一个问题：插入到博客中的gif动图播放一遍就结束了，也就是说不能循环播放，导致的结果是，当你刚打开网页，可能这张图片就悄悄地播放结束了，显然者和我们要的效果违背了。可是我又想了想，之前在公众号写博客的时候，同样的动图都是可以循环播放的。所以我才想这可能是微信和网页端的框架不同吧。所以抱着解决这个问题的态度，我就上网搜了搜。很幸运，找到了解决方案，正因此才有了今天的这篇更新，希望对你有用。具体方法如下：

**Comment by DiYingisaDer** [comment]
感谢
